#!/usr/bin/env python

import sys
import os
import os.path as osp
import imp

default_args = [('--db_host','mysql'),
                ('--db_user','root'),
                ('--db_passwd',os.environ.get('MYSQL_ROOT_PASSWORD')),             
                ('--project_root',None)]

custom_args=[a for a,_ in default_args if a in sys.argv[1:]]

if len(custom_args)>0: 
    print "\033[33mWARNING: Using custom arg(s) %s which may break the default boinc-server-docker configuration unless you know what you're doing!\033[0m"%custom_args

os.chdir('boinc/tools')

sys.argv = (['make_project']+
            sum([[k,v] for k,v in default_args if v and k not in sys.argv],[])+
            sys.argv[1:])

print ' '.join(sys.argv)

sys.path += ['.']
sys.dont_write_bytecode = True #avoid creating make_projectc file
make_project = imp.load_source('make_project', 'make_project')

project_root = make_project.options.project_root
conf_file = make_project.httpd_conf_template_filename

with open(conf_file) as f:
    conf=f.read().replace("Order allow,deny\n        Allow from all","Require all granted")
with open(conf_file,"w") as f:
    f.write(conf)


sym_target = osp.join("/etc/apache2/sites-enabled/",osp.basename(conf_file))
if not osp.exists(sym_target): 
    try:
        os.symlink(os.path.abspath(conf_file),sym_target)
    except:
        print "Failed to link '%s' to apache directory. You will need to add this file manually."%conf_file

