#!/bin/sh

set -e

TAG=${1:-marius311/camb_boinc2docker:latest}

DEVTAG=camb_boinc2docker_develop

docker build -t $DEVTAG develop
docker run -v $(readlink -f release):/release --rm -t $DEVTAG
docker build -t $TAG release
