#!/bin/sh

set -e

str=$(git describe --match "camb_boinc2docker/*" --abbrev=0 --tags)
VERSION=${str#*/}

TAG=${1:-marius311/camb_boinc2docker:$VERSION}

DEVTAG=camb_boinc2docker_develop

docker build -t $DEVTAG develop
docker run -v $(readlink -f release):/release --rm -t $DEVTAG
docker build -t $TAG release

echo "Maybe push image now...?"
echo "docker push $TAG"
