#!/bin/sh

set -e 

tar zxvf /root/shared/params -C /root/shared
docker pull marius311/camb_boinc2docker:test
save_docker.sh
docker run -v /root/shared:/root/shared -v /tmp:/tmp marius311/camb_boinc2docker:test /root/shared/params*.ini
