<?php

$project_news = array(
  array(
        "Jul 13, 2015",
        "A new <a href=\"http://cosmicmar.com/2015/07/13/stats-about-cosmology-at-home\"/>post</a> containing statistics about Cosmology@Home users. Discussion <a href=\"http://www.cosmologyathome.org/forum_thread.php?id=7225\">here</a>.",
        "Stats about Cosmology@Home"),
  array(
        "Jul 10, 2012",
        "Kevin implemented further fixes to the web site and the server software. The participant profiles can now be browsed through the web site. Spam profiles have been removed. Upload errors should have been cured. Please test and let us know what you find. ",
        "Website and server bug fixes"),
  array(
        "Jun 20, 2012",
        "A major update has now been completed - the HTML/PHP for the website has now been updated to the latest version. This was long overdue and has hopefully closed some security loopholes. We are now cleaning out a backlog of spam user profiles, etc. Please let us know if anything is not working as expected as a consequence of these updates..",
        "Further updates"),
   array(
        "May 6, 2012",
        "As part of the recent updates (more storage, more recent kernel) we finally fixed a longstanding problem: the community preferences are now working again! Check out our main post on the message board for the project announcements.",
        "Recent updates and fixes to the project"),
   array(
        "April 17, 2012",
        "We updated the featured concept to Dark Matter, with a cool image of the bullet cluster. At the bottom of the featured concept on the home page there is a link that will take you to a thread on the message board where you can comment and ask questions. Enjoy!",
        "New featured concept: Dark Matter"),
   array(
        "April 10, 2012",
        "After installation of 4TB of disk space and a re-organization of the file system, and a few updates and bug fixes, such as updating the data base to fix an annoying and persistent problem with setting user preferences,  we are back in production. Thank you for your patience and keep crunching!",
        "Server upgrade complete."),
  array(
        "March 2, 2012",
        "We are running again, with a temporary fix for the disk space problem. 4 TB of disk space have been ordered. The team data base has been repaired. We will keep you updated when the filesystem upgrade happens, which we will take as an opportunity for a few additional updates.",
        "We\'re back."),
   array(
        "February 7, 2012",
        "As some of you have pointed out, we are currently experiencing problems with the file system which are affecting the module that assimilates the results of your computations. We are working to resolve these problems and will endeavor to keep you updated as we progress. Please bear with us as we try to resolve this problem.  ",
        "Assimilator not working - update 1."),
   array(
        "October 17, 2011",
        "<a href=\"http://www.cosmologyathome.org/forum_thread.php?id=864\">Please join Ben in welcoming Faik</a>, a new member of the cosmology@home team.",
        "New team member!"),
  array(
        "October 4, 2011",
        "In honor of today's Physics Nobel Prize winners our Featured Concept on the home page now discusses type Ia supernovae, exploding white dwarfs that were key to the discovery of the  accelerated expansion of the Universe.",
        "Featured Concept changed to Type Ia SuperNovae"),
  array(
        "October 4, 2011",
        "Congratulations to Saul Perlmutter, Brian Schmidt and Adam Riess! <a href=\"http://cosmologyathome.org/forum_forum.php?id=11\">Read Ben's post about today's Physics Nobel Prize</a>.",
        "Physics Nobel Prize goes to Cosmology!"),
  array(
        "August 18, 2011",
        "We invited the other members of the US Planck team to participate in the user community of cosmology@home. Please fill in this <a href=\"http://www.surveymonkey.com/s/KNRKVXS\">survey</a> to comment on what features you would like to see most.",
        "Feedback to Planck Mission Education group"),
   array(
        "December 23, 2010",
        "Updated our Featured Concept. This was long overdue and will now occur semi-regularly. The more popular demand, the more frequent the updates. Let me know by posting on the message boards what concepts you would like to see discussed.",
        "Featured Concept updated"),
  array(
        "December 20, 2010",
        "Planck completes its baseline survey - now in extended mission. ESA announced mission extension until 2014! Follow the Planck mission at <a href=\"http://sci.esa.int/science-e/www/area/index.cfm?fareaid=17\">this website</a>.",
        "Great news about the Planck mission!"),
  array(
        "December 20, 2010",
        "Fixed several bugs on the site caused by migration from *.uiuc.edu to *.illinois.edu, plus a few others. Watch for further updates.",
        "Several website bugs fixed"),
  array(
        "April 28, 2009",
        "A total of 5000 credits have been added to profiles of all active Cosmo@home users. This is meant for expired/failed WUs due to project down-time and to compensate for the earlier low credit per WU payment for resource intensive CAMB 2.16 WUs. Also, the time bound for these new WUs has been increased from 10 days to 15 days which should be enough to complete crunching them even on machines ~5 years old.",
        "Credit and Time Bound issues"),
  array(
        "April 18, 2009",
        "We have restored CAMB 2.16 apps successfully for all platforms so all project specific errors (Signature and/or Checksum) should no longer be present. Also, most WUs for camb 2.16 are more resource heavy than the previous WU's for 2.15 so we have increased the credit for each WU from 140 to 200. If there are any disputes about this we will be happy to address them. If you feel that the credit being given for the 2.16 app, WUs is too little/ too much please start a thread related to this on the Wish List message board. Thank you.",
        "Apps restored successfully and increase in credits"),
  array(
        "March 27, 2009",
        "After replacing a damaged RAID drive, the server kept throwing I/O errors and kernel panics, which required us to have the motherboard and RAID controller replaced as well. Hopefully this last round of hardware replacements will solve the problem and we will be back up today.",
        "More hardware maintenance"),
    array(
        "March 26, 2009",
        "The website is mostly up and running at the moment. We'll have the project daemons up as soon as possible.",
        "Website back up"),
    array(
        "March 13, 2009",
        "The Cosmology@home server has been suffering abnormal crashes ever few hours since the campus power outage on March 8, 2009. We will be taking to server offline soon for maintanence and repairs during which time Cosmolosy@home will not run. This website and the forums will also not be accessible at that time. We are working as fast as possible to get the project back up and running to its full potential.",
        "C@H down for server maintanence"),
    array(
        "March 8, 2009",
        "There had been a power outage at the University of Illinois campus today for approximately 12 hours due to strong winds knocking down large power lines in the county. Due to this some of you may have experienced download problems from Cosmo@home over the course of the day but the power has now been restored and everything should be back to normal. If someone still experiences problems please let us know through the forums. Thank you.",
        "Power outage on campus"),
    array(
        "March 3, 2009",
        "A problem which was causing the test parameter file generator to output empty parameter files has been corrected. I just tested a new test WU on my machine and it seems to be working file. I'll be creating another 500 WUs to test the app on other architectures. The credit for these WUs (excluding the 5 that I just made to test whether parameter file generation was working correctly) will be 3 times the normal amount.",
        "Test parameter file generator fixed"),
    array(
        "March 2, 2009",
        "We're in the process of debugging the test app. There will periodically be test WUs released in small batches to test the new app version. The new WUs should require lower accuracy and should complete more quickly than the last batch.<br/><br/>
        Credit will be given out for successfully completed WUs (that is, WUs without errors). However, we'd like to remind everybody that credit is not guaranteed for test WUs. Test WUs help us to release new versions of CAMB and keep C@H going; be aware, however, that these WUs can (and often do) fail, so if you would rather crunch regular WUs and not have to deal with the hassle of failed WUs, then disable test work in your project preferences. Crunching test WUs will never be compulsory. That being said, however, we will make every effort to reward users who donate their CPU time to help us test.",
        "Testing in the future"),
    array(
        "February 24, 2009",
        "A new test application has been released and 500 test WUs created. Please enable test work in your project preferences if you would like to help us test this new version so we can put it into production.",
        "New test application released"),
    array(
        "February 17, 2009",
        "All Cosmology hosts are now visible in stat sites. The database was curropted due to the server crash last November and has now been fixed.",
        "Cosmo hosts back up on stat sites"), 
    array(
        "February 2, 2009",
        "We are hiring - please look at the <a href=\"http://cosmos.astro.illinois.edu/job_posting.pdf\">job posting</a> for more information.",
        "Cosmology@Home is hiring!"),
    array(
        "December 10, 2008",
        "Our new validator has completed its testing phase and is finally ready to go live! An important new feature of this validator is that it eliminates the need for homogenous redundancy and sets quorum of all WUs to 1. As with any major update there may be bugs so we request your help in identifying them. Thanks and Merry Christmas!",
        "New Validator to go online at midnight"),
    array(
        "November 29, 2008",
        "Once again, the ghosts in the machine attacked when everybody was out of town for Thanksgiving, rendering the server non-functional until someone could make it back in town. After replacing the network switch and the NIC, and applying a hefty dose of holy water to ward away any further geist attacks, the server is up again.",
        "Server back up after Thanksgiving outage"),
    array(
        "November 15, 2008",
        "We have generated 50 test work units each worth 120 credits to test our new validator. The new validator essentially eliminates the need for homogenous redundancy and will also be used to organize our data more efficiently. Checking to see if these test work units download correctly will also help us narrow down possibilities and help find a solution to the HTTP errors many of you have been experiencing with this project.<br />-Anshul",
        "New Validator and HTTP error issues"),
    array(
        "October 18, 2008",
        "Fixed a problem with the work generator and made approximately 10k new WUs. Sorry for the inconvenience.<br/>-Scott",
        "Fixed WU Generator Issue"),
    array(
        "October 15, 2008",
        "The WUs for the test application have been removed and we have started up the work generator. You should see regular WU traffic soon.",
        "Old test WUs removed and Work Generator started."
        ),
    array(
        "October 10, 2008",
        "The old WUs are still around, since I made a mistake in the script used to cancel them, so I've just manually cancelled all of the old ones again. This shouldn't affect the new WUs at all.",
        "Old WUs Re-cancelled"),
    array(
        "October 10, 2008",
        "Making some work today (for the main app) to test the new validation system. If the work starts to come back properly, then we'll start making more.",
        "Work today"),
    array(
        "October 4, 2008",
        "Anshul and I are going to spend the day working on the project. The first thing will be to clear out the WU queue and start from scratch. We'll keep you posted.",
        "Maintenance today"),
    array(
        "September 30, 2008",
        "We've just hired a new administrator for Cosmology@Home, Anshul Kanakia. I will be working with him in the next couple of weeks to get the project up and running. Anshul is an undergraduate at the Univerisity of Illinois, so he will have as much time (or more) than I had in the past to dedicate to the project. Please welcome him and help him out if you can!",
        "New Administrator"),
    array(
        "September 5, 2008",
        "It should also be noted that test work will be validated regardless of whether or not it matches the partner WU. This will insure that nobody is penalized for running test work with the experimental HR.",
        "Another note about test work"),
    array(
        "September 5, 2008",
        "After a little more work, we are going to release some work for the test app test_camb, which will be using a different (although not final) version of HR. The credit for these WUs will be higher than that for normal WUs (140 versus 120). If you want to participate in testing, please enable test work in your project preferences.<br/><br/>NOTE: This post has been edited to reflect the correct credit values.",
        "Test work"),
    array(
        "September 3, 2008",
        "The RAID array on our server broke down over the weekend, and after an incredibly-long recovery process, the server is back up.",
        "Server back up after hardware problems"),
    array(
        "August 29, 2008",
        "The projct will be down while we work on the major problems facing the project right now, including work distribution, HR, and credit. We will be making work for a test application so we can test the new HR model.",
        "Project overhaul and application testing"),
    array(
        "August 9, 2008",
        "Workunits created over two weeks ago have been piling up, so we've made a small change to the feeder code and cancelled the offending WUs.",
        "Old WUs cancalled and feeder code modified"),
    array(
        "July 31, 2008",
        "The i686 Linux app issue has been fixed.",
        "Linux app issue fixed"),
    array(
        "July 24, 2008",
        "Due to a typo in the work-generation script and non-aggressive PHP error checking, work generation was down yesterday. It's been fixed now.",
        "Work generator fixed"),
    array(
        "July 22, 2008",
        "The new CAMB is now up and work generation has commenced; in addition, credit for the new WUs has been increased, since lensing is now re-enabled.<br/><br/>Although we let the old WUs drain as much as possible, there may yet still be some in the queue, which may cause some problems with the new CAMB. TTherefore, if you get work that is dated before the 22nd, you may want to play it safe and abort the WU.",
        "New CAMB, work generation, increased credit, and old WUs."),
    array(
        "July 22, 2008",
        "We are nearly done with the new CAMB app with lensing, so it should be up later on today along with the new parameter generator.",
        "New CAMB version and work generation later on today"),
    array(
        "July 14, 2008",
        "The number of WUs awaiting validation is now under 2000, so we should be back in business soon. We've also fixed the lensing problem with CAMB, so we'll be releasing a new app version soon. Before that, however, we have to let the work queue drain a bit, so we'll be keeping the WU generator offline until the queue goes back to normal.",
        "WU validation and fixed CAMB application"),
    array(
        "July 12, 2008",
        "The server is back up after being shut down during some thunderstorms in Champaign-Urbana this afternoon.",
        "Server back up after thunderstorms"),
    array(
        "July 10, 2008",
        "We're going to shut down the scheduler for a couple of hours so that the validator can deal with the significant increase in traffic.",
        "Letting the validator catch up"),
    array(
        "July 9, 2008",
        "The database is having some issues currently, so we will be bringing it down for a little while to investigate.",
        "Database maintenance."),
    array(
        "July 4, 2008",
        "There will be a bit of down time later tonight while we tweak the database a bit.",
        "Down-time tonight"),
    array(
        "June 18, 2008",
        "For those who prefer the old design, it is currently accessible <a href=\"http://www.cosmologyathome.org/testsite\">here</a>.",
        "Old design is still available"),
    array(
        "June 16, 2008",
        "The new website design is up. Please report any bugs on the forums.",
        "New website design is up"),
    array(
        "May 13, 2008",
        "We've got the stats working again and we've cancelled all of the WUs that were created yesterday that were erroring out.",
        "Stats and WU Errors"),
    array(
        "May 13, 2008",
        "Recompiled the work generator to work with the server OS upgrades, so the new WUs should work fine. I'm now looking getting the stats export to work again.",
        "WU generator fixed and working on stats exporting"),
    array(
        "May 13, 2008",
        "I've seen the errors with the new WUs and I will take care of it first thing in the morning.",
        "WU Errors"),
    array(
        "May 12, 2008",
        "OK, now the work generator is *really* up.",
        "Work generator up, really"),
    array(
        "May 11, 2008",
        "It looks like work is flowing a bit better now, so I'm going to restart the work generator and see what happens.",
        "Work generator back online"),
    array(
        "May 10, 2008",
        "After more work, the source of a number of the database and bandwidth errors were located and fixed. Please report if the situation pops up again.",
        "Database and Bandwidth errors"),
    array(
        "May 9, 2008",
        "The project daemons seems to be mostly working at this point. There are still some problems with scheduling, though, and there are *far* too many WUs in the queue due to the population script not being able to get queries out in time, so we're going to wait a while to see if it settles. However, it looks like the database is doing *much* better and there are no hanging queries. I'll keep you posted on changes.",
        "Another update"),
    array(
        "May 9, 2008",
        "Still having problems with the validator. After I grab some shut-eye, I'll work on it some more (it's only permission problems).",
        "Break for a while"),
    array(
        "May 9, 2008",
        "After much shenanigans, logging in is now working again, so the message board is up. Still working on the rest.",
        "Update"),
    array(
        "May 9, 2008",
        "The website is mostly up right now, but I'm still ironing out some bugs having to do with logging in. The project daemons seems to be up and running but I haven't verified that they are working properly yet. More updates to come.",
        "Maintainence Updates"),
    array(
        "May 8, 2008",
        "Project will be going down later on today. Since we'll be doing OS updates, the web server will also be down.",
        "Project down later on today"),
    array(
        "May 5, 2008",
        "On Thursday, May 8, we will be bringing down the server for most of the day to perform the maintainence we previous mentioned.",
        "Maintainence this week"),
    array(
        "April 20, 2008",
        "Early next month, we plan on performing some major maintainence on our server hardware which will require that we shut down the server for a number of hours. We'll give a more specific date around that time, but we thought you all would appreciate the heads up.",
        "Maintainence and downtime in the next couple of weeks"),
    array(
        "April 7, 2008",
        "We're finished with the database maintainence for now. Some more may be required tomorrow as well, if the database keeps acting up.",
        "Maintainence finished for now"),
    array(
        "April 7, 2008",
        "Since CAMB sans lensing seems to be much, MUCH faster than CAMB with lensing, we're temporarily lowered the credit again to 50, which still is pretty high, just not ridiculous like it is now.",
        "Temporarily lowering credit again"),
    array(
        "April 7, 2008",
        "The scheduler will be down for a little while while we tool around with the database in order to fix the slow query issue.",
        "Scheduler temporarily down"),
    array(
        "April 5, 2008",
        "<a href=\"http://www.cosmologyathome.org/forum_thread.php?id=21&nowrap=true#5803\">A message to Cosmology@Home users</a>",
        "A message to Cosmology@Home users"),
    array(
        "April 5, 2008",
        "We've been working on the server for the past week every day trying to get the server back to an acceptable state. However, the database has been extremely stubborn in going back to normal. We will continue to work on it *every day* until it's 100% right, so please don't think that we are unaware or or ignoring the problems.",
        "We're Still Here"),
    array(
        "April 4, 2008",
        "The database activity has finally gone down to an acceptable level, so we've restarted the project daemons.",
        "Project Daemons Restarted"),
    array(
        "April 2, 2008",
        "Due to the flux in workunits that has been taking place recently, there's quite a lot of strain on the database. So, until the validator and the other daemons are caught up on their work, we aren't going to send out any more WUs. We'll restart the scheduler as soon as it's done. Thank you for your patience.",
        "Letting the validator catch up"),
    array(
        "April 1, 2008",
        "The database appears to be up and working again. To learn more about the issues, read <a href=\"http://www.cosmologyathome.org/forum_thread.php?id=140&nowrap=true#5640\">this post</a>.",
        "Update on the database situation"),
    array(
        "March 31, 2008",
        "We are experiencing some problems with our mysql server which started at some point over the weekend. I am currently working on it and will post as soon as I have it up again.",
        "Problems with mysql server"),
    array(
        "March 26, 2008",
        "Despite temporarily disabling the lensing component of CAMB, the results are still very useful to us, so please don't worry that your time here at Cosmology@Home is wasted.",
        "Keep on Crunching!"),
    array(
        "March 26, 2008",
        "Until we fix CAMB's lensing component, we will be temporarily lowering credit granted to all WUs from 100 to 80.",
        "Temporarily lowering credit from non-lensing CAMB WUs"),
    array(
        "March 20, 2008",
        "It seems that the WUs in the queue right now will not run correctly, so we are going to cancel all of the current WUs and give credit to the WUs which have already been completed. Then, we will enable the new WU generator. Make sure to update your BOINC client so that you don't accidentally crunch WUs that have been canceled.",
        "Canceling Old Workunits"),
    array(
        "March 19, 2008",
        "The project is now back up and running. The generator will be down for a bit until we run down the available WUs, but then the new generator will kick in.",
        "Project daemons back up and running"),
    array(
        "March 18, 2008",
        "We are suspending WU generation until the \"Rombint\" errors are solved and a new generator is up and running.",
        "Project Temporarily Suspended"),
    array(
        "March 15, 2008",
        "The server is back up after cleaning out the old versions of CAMB that are no longer being used.",
        "Server is back up"),
    array(
        "March 14, 2008",
        "CAMB 2.12 has been released and now correctly resolves the output filenames to prevent \"cannot rename output file\" errors.",
        "Fix for the output file errors released"),
    array(
        "March 11, 2008",
        "If you are experiencing problems with CAMB 2.10 and below, abort those WUs and get the newest version of CAMB, 2.11",
        "Upgrade To CAMB 2.11"),
    array(
        "January 24, 2008",
        "An update about the current server situation is <a href=\"http://cosmologyathome.org/forum_thread.php?id=353&nowrap=true#4687\">here</a>.",
        "Update on the Server Situation"),
    array(
        "January 24, 2008",
        "Note that between today and tomorrow, the site URL might change between \"www.cosmologyathome.org\" and \"cosmologyathome.org\", although they are more or less equivalent. Tomorrow night, it should stay permanently at the former one. Sorry for any confusion this may cause.",
        "Permanent URL"),
    array(
        "January 24, 2008",
        "There have been a lot of problems caused by the move across servers, mostly caused by complications with apache and the BOINC client. I've spent most of my day working on a solution, which I will outline <a href=\"http://cosmologyathome.org/forum_thread.php?id=21&nowrap=true#4621\">here</a>.",
        "Server Issues and Solutions"),
    array(
        "January 18, 2008",
        "On the coming Wednesday (1/23/2008), we will be performing some server maintenence at 5 PM CST (11 PM UTC). The server may be down for a period of a couple of hours, but I'll try to get it back up and running ASAP.",
        "Server Maintenence"),
    
);

?>
