#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Cosmology@Home Blog 

# Short bio or description (displayed in the header)
description: News and Updates From The CAH Team

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: http://cosmos.astro.illinois.edu/images/people/p_ben.jpg
#https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: bwandelt@illinois.edu
  facebook:
  flickr:
  github: #barryclark/jekyll-now
  instagram:
  linkedin: /profile/view?id=21341148
  pinterest:
  rss: /rss_main.php # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: bwandelt #jekyllrb
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
        url: http://www.cosmologyathome.org/blog

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!


# Where things are
source:      . #../blog/jekyll_source # .
destination: ../blog-stage #_site
#data_source: _data #../blog/blog-dev #_data

markdown: redcarpet
highlighter: pygments
permalink: /blog/:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _sass
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

